import { Rule } from '../../types';

/**
 * Database connection URI and credential patterns.
 */
export const databaseRules: Rule[] = [
  {
    id: 'db-postgres-uri',
    description: 'PostgreSQL connection URI with credentials',
    pattern: /(?:database[_-]?url|db[_-]?url|postgres(?:ql)?[_-]?(?:url|uri)|DATABASE_URL)\s*[:=]\s*['"\`](postgres(?:ql)?:\/\/[^'"\`\s]+:[^'"\`\s]+@[^'"\`\s]+)['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'DATABASE_URL',
    severity: 'critical',
  },
  {
    id: 'db-mysql-uri',
    description: 'MySQL connection URI with credentials',
    pattern: /(?:database[_-]?url|db[_-]?url|mysql[_-]?(?:url|uri)|MYSQL_URI)\s*[:=]\s*['"\`](mysql(?:2)?:\/\/[^'"\`\s]+:[^'"\`\s]+@[^'"\`\s]+)['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'MYSQL_URL',
    severity: 'critical',
  },
  {
    id: 'db-mysql-uri-bare',
    description: 'Bare MySQL URI (any variable name)',
    pattern: /['"\`](mysql(?:2)?:\/\/[^'"\`\s]+:[^'"\`\s]+@[^'"\`\s]+)['"\`]/,
    valueGroup: 1,
    envKeyPrefix: 'MYSQL_URL',
    severity: 'critical',
  },
  {
    id: 'db-mongodb-uri',
    description: 'MongoDB connection URI with credentials',
    pattern: /(?:mongo(?:db)?[_-]?(?:url|uri)|MONGO(?:DB)?_URI|MONGODB_URI)\s*[:=]\s*['"\`](mongodb(?:\+srv)?:\/\/[^'"\`\s]+:[^'"\`\s]+@[^'"\`\s]+)['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'MONGODB_URI',
    severity: 'critical',
  },
  {
    id: 'db-mongodb-uri-bare',
    description: 'Bare MongoDB URI (any variable name)',
    pattern: /['"\`](mongodb(?:\+srv)?:\/\/[^'"\`\s]+:[^'"\`\s]+@[^'"\`\s]+)['"\`]/,
    valueGroup: 1,
    envKeyPrefix: 'MONGODB_URI',
    severity: 'critical',
  },
  {
    id: 'db-redis-uri',
    description: 'Redis connection URI with credentials',
    pattern: /(?:redis[_-]?(?:url|uri)|REDIS_URL|REDIS_URI)\s*[:=]\s*['"\`](rediss?:\/\/(?:[^'"\`\s]+:[^'"\`\s]+@)?[^'"\`\s]+)['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'REDIS_URL',
    severity: 'critical',
  },
  {
    id: 'db-redis-uri-bare',
    description: 'Bare Redis URI (any variable name, including password-only form)',
    pattern: /['"\`](rediss?:\/\/[^'"\`\s]*:[^'"\`\s]*@[^'"\`\s]+)['"\`]/,
    valueGroup: 1,
    envKeyPrefix: 'REDIS_URL',
    severity: 'critical',
  },
  {
    id: 'db-rabbitmq-uri',
    description: 'RabbitMQ / AMQP connection URI with credentials',
    pattern: /(?:rabbitmq[_-]?(?:url|uri)|amqp[_-]?(?:url|uri)|RABBITMQ_URL|AMQP_URL|RABBITMQ_URI)\s*[:=]\s*['"\`](amqps?:\/\/[^'"\`\s]+:[^'"\`\s]+@[^'"\`\s]+)['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'RABBITMQ_URL',
    severity: 'critical',
  },
  {
    id: 'db-rabbitmq-uri-bare',
    description: 'Bare RabbitMQ/AMQP URI (any variable name)',
    pattern: /['"\`](amqps?:\/\/[^'"\`\s]+:[^'"\`\s]+@[^'"\`\s]+)['"\`]/,
    valueGroup: 1,
    envKeyPrefix: 'RABBITMQ_URL',
    severity: 'critical',
  },
  {
    id: 'db-password',
    description: 'Database password assignment (any service-prefixed _PASSWORD variable)',
    pattern: /(?:db[_-]?pass(?:word)?|database[_-]?pass(?:word)?|replica[_-]?pass(?:word)?|mysql[_-]?pass(?:word)?|redis[_-]?pass(?:word)?|mongo(?:db)?[_-]?pass(?:word)?|postgres(?:ql)?[_-]?pass(?:word)?|mssql[_-]?pass(?:word)?|rabbit(?:mq)?[_-]?pass(?:word)?|elastic(?:search)?[_-]?pass(?:word)?|DB_PASSWORD|DATABASE_PASSWORD|MYSQL_PASSWORD|REDIS_PASSWORD|MONGODB_PASSWORD|MSSQL_PASSWORD|RABBITMQ_PASSWORD|ELASTICSEARCH_PASSWORD|REPLICA_PASSWORD)\s*[:=,]\s*['"\`]([^'"\`\n]{4,})['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'DB_PASSWORD',
    severity: 'critical',
  },
  {
    id: 'db-username',
    description: 'Database username assignment',
    pattern: /(?:db[_-]?user(?:name)?|database[_-]?user(?:name)?|DB_USER(?:NAME)?|DATABASE_USER(?:NAME)?)\s*[:=]\s*['"\`]([^'"\`\n]{2,})['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'DB_USERNAME',
    severity: 'medium',
  },
  {
    id: 'db-host',
    description: 'Database host assignment (non-localhost)',
    pattern: /(?:db[_-]?host|database[_-]?host|DB_HOST|DATABASE_HOST)\s*[:=]\s*['"\`]((?!localhost|127\.0\.0\.1|0\.0\.0\.0)[^'"\`\n]{4,})['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'DB_HOST',
    severity: 'medium',
  },
  {
    id: 'db-sqlite-path',
    description: 'SQLite database file path',
    pattern: /(?:sqlite[_-]?(?:url|path|db)|DATABASE_URL)\s*[:=]\s*['"\`](sqlite(?:3)?:\/\/\/[^'"\`\s]+\.db)['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'SQLITE_PATH',
    severity: 'low',
  },
  {
    // Captures the ENTIRE connection string between double-quotes so the rewriter
    // replaces the full literal value — not a truncated portion stopping at Password=.
    id: 'db-mssql-connection-double-quote',
    description: 'Microsoft SQL Server connection string in double quotes',
    pattern: /(?:mssql[_-]?connection[_-]?(?:string)?|MSSQL_CONNECTION_STRING|connection[_-]?string)\s*[:=,]\s*"(Server=[^"]+Password=[^"]+)"/i,
    valueGroup: 1,
    envKeyPrefix: 'MSSQL_CONNECTION_STRING',
    severity: 'critical',
  },
  {
    id: 'db-mssql-connection-single-quote',
    description: 'Microsoft SQL Server connection string in single quotes',
    pattern: /(?:mssql[_-]?connection[_-]?(?:string)?|MSSQL_CONNECTION_STRING|connection[_-]?string)\s*[:=,]\s*'(Server=[^']+Password=[^']+)'/i,
    valueGroup: 1,
    envKeyPrefix: 'MSSQL_CONNECTION_STRING',
    severity: 'critical',
  },
  {
    id: 'db-mssql-connection-bare',
    description: 'Microsoft SQL Server connection string (unquoted, e.g. in .env files)',
    // Stops at whitespace and quote chars; does NOT stop at ; so the full string is captured.
    pattern: /(Server=[^;\s'"]+;(?:Database=[^;]+;)?User\s*Id=[^;]+;Password=[^;\s'"]+)/i,
    valueGroup: 1,
    envKeyPrefix: 'MSSQL_CONNECTION_STRING',
    severity: 'critical',
  },
  {
    id: 'db-elasticsearch-uri',
    description: 'Elasticsearch connection URI with credentials',
    pattern: /(?:elastic(?:search)?[_-]?(?:url|uri)|ELASTICSEARCH_URL|ELASTICSEARCH_URI)\s*[:=]\s*['"\`](https?:\/\/[^'"\`\s]+:[^'"\`\s]+@[^'"\`\s]+)['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'ELASTICSEARCH_URL',
    severity: 'critical',
  },
  {
    id: 'db-elasticsearch-api-key',
    description: 'Elasticsearch API key (base64 encoded)',
    pattern: /(?:elastic(?:search)?[_-]?api[_-]?key|ELASTICSEARCH_API_KEY)\s*[:=,]\s*['"\`]([A-Za-z0-9+/=]{20,})['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'ELASTICSEARCH_API_KEY',
    severity: 'critical',
  },
  {
    id: 'db-cassandra-credentials',
    description: 'Cassandra username or password assignment',
    pattern: /(?:cassandra[_-]?(?:user(?:name)?|pass(?:word)?)|CASSANDRA_(?:USERNAME|PASSWORD))\s*[:=]\s*['"\`]([^'"\`\n]{4,})['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'CASSANDRA_CREDENTIALS',
    severity: 'critical',
  },
  {
    id: 'db-oracle-connection',
    description: 'Oracle DB connection string or credentials',
    pattern: /(?:oracle[_-]?(?:url|uri|connection)|DATA_SOURCE_NAME)\s*[:=]\s*['"\`]([^'"\`\n]{8,})['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'ORACLE_CONNECTION_STRING',
    severity: 'critical',
  },
  {
    id: 'db-generic-dsn',
    description: 'Generic DSN (Data Source Name) with embedded credentials',
    pattern: /(?:dsn|data[_-]?source[_-]?name)\s*[:=]\s*['"\`]([^'"\`\n]{8,})['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'DSN',
    severity: 'critical',
  },
  {
    id: 'db-cockroachdb-uri',
    description: 'CockroachDB connection URI with credentials',
    pattern: /(?:cockroach(?:db)?[_-]?(?:url|uri)|COCKROACHDB_URL)\s*[:=]\s*['"\`](cockroachdb:\/\/[^'"\`\s]+:[^'"\`\s]+@[^'"\`\s]+)['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'COCKROACHDB_URL',
    severity: 'critical',
  },
  {
    id: 'db-kafka-sasl-password',
    description: 'Kafka SASL password or credentials',
    pattern: /(?:kafka[_-]?(?:sasl[_-]?)?(?:password|pass|secret)|KAFKA_PASSWORD|KAFKA_SASL_PASSWORD)\s*[:=]\s*['"\`]([^'"\`\n]{4,})['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'KAFKA_PASSWORD',
    severity: 'critical',
  },
  {
    id: 'db-dynamodb-endpoint',
    description: 'DynamoDB custom endpoint (non-AWS, e.g., local or 3rd-party)',
    pattern: /(?:dynamodb[_-]?endpoint|DYNAMODB_ENDPOINT)\s*[:=]\s*['"\`](https?:\/\/(?!localhost|127\.0\.0\.1)[^'"\`\s]+)['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'DYNAMODB_ENDPOINT',
    severity: 'medium',
  },
  {
    id: 'db-neo4j-uri',
    description: 'Neo4j graph database connection URI with credentials',
    pattern: /(?:neo4j[_-]?(?:url|uri|bolt)|NEO4J_URI)\s*[:=]\s*['"\`](bolt(?:\+ssc)?:\/\/[^'"\`\s]+:[^'"\`\s]+@[^'"\`\s]+)['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'NEO4J_URI',
    severity: 'critical',
  },
  {
    id: 'db-influxdb-token',
    description: 'InfluxDB authentication token',
    pattern: /(?:influxdb?[_-]?token|INFLUX(?:DB)?_TOKEN)\s*[:=]\s*['"\`]([A-Za-z0-9\-_=]{16,})['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'INFLUXDB_TOKEN',
    severity: 'critical',
  },

  // ClickHouse credentials
  {
    id: 'db-clickhouse-credentials',
    description: 'ClickHouse HTTP connection URI or credentials',
    pattern: /(?:clickhouse[_-]?(?:url|uri|password)|CLICKHOUSE_URL|CLICKHOUSE_PASSWORD)\s*[:=]\s*['"\`]([^'"\`\n]{8,})['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'CLICKHOUSE_URL',
    severity: 'critical',
  },
  // CouchDB URI
  {
    id: 'db-couchdb-uri',
    description: 'CouchDB connection URI with credentials',
    pattern: /(?:couchdb[_-]?(?:url|uri)|COUCHDB_URL)\s*[:=]\s*['"\`](https?:\/\/[^'"\`\s]+:[^'"\`\s]+@[^'"\`\s]+)['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'COUCHDB_URL',
    severity: 'critical',
  },
  // etcd password
  {
    id: 'db-etcd-password',
    description: 'etcd cluster password (common in Kubernetes configs)',
    pattern: /(?:etcd[_-]?(?:password|pass)|ETCD_PASSWORD)\s*[:=]\s*['"\`]([^'"\`\n]{4,})['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'ETCD_PASSWORD',
    severity: 'critical',
  },
  // LDAP inline DN password
  {
    id: 'db-ldap-password-inline',
    description: 'LDAP credentials embedded inline in a DN string',
    pattern: /(?:ldap[_-]?bind[_-]?dn|LDAP_BIND_DN)\s*[:=]\s*['"\`]([^'"\`\n]*(?:password|pass)=[^'"\`\n]{4,})['"\`]/i,
    valueGroup: 1,
    envKeyPrefix: 'LDAP_BIND_DN',
    severity: 'critical',
  },

  // ── Apache Cassandra ──────────────────────────────────────────────────────────
  {
    id: 'db-cassandra-password',
    description: 'Apache Cassandra database password',
    pattern: /(?:cassandra[_-]?(?:password|pass)|CASSANDRA_PASSWORD)\s*[:=]\s*['"`]([^'"`\n]{4,})['"`]/i,
    valueGroup: 1,
    envKeyPrefix: 'CASSANDRA_PASSWORD',
    severity: 'critical',
  },

  // ── Couchbase ─────────────────────────────────────────────────────────────────
  {
    id: 'db-couchbase-password',
    description: 'Couchbase database password or connection URL',
    pattern: /(?:couchbase[_-]?(?:password|pass|url|uri)|COUCHBASE_PASSWORD|COUCHBASE_URL)\s*[:=]\s*['"`]([^'"`\n]{4,})['"`]/i,
    valueGroup: 1,
    envKeyPrefix: 'COUCHBASE_PASSWORD',
    severity: 'critical',
  },

  // ── ScyllaDB ──────────────────────────────────────────────────────────────────
  {
    id: 'db-scylladb-password',
    description: 'ScyllaDB database password',
    pattern: /(?:scylla(?:db)?[_-]?(?:password|pass)|SCYLLADB_PASSWORD|SCYLLA_PASSWORD)\s*[:=]\s*['"`]([^'"`\n]{4,})['"`]/i,
    valueGroup: 1,
    envKeyPrefix: 'SCYLLADB_PASSWORD',
    severity: 'critical',
  },

];
